### ISSUE TITLE
Logging functions with lower priority than the configured log level do not work properly

### ISSUE THREAD

**Issue by not-an-aardvark** [Kikobeats/sails-hook-winston#10]
I have a server with log level set to `info`. When using sails without this hook, I can use `sails.log.debug` to output information to the console, because the `info` log level is higher than the `debug` log level on [this page](http://sailsjs.org/documentation/concepts/logging). However, with this hook installed, `sails.log.debug` does not generate any output.

I'm using sails 0.11.5 and sails-hook-winston 1.0.0.

---

config/log.js:

``` js
module.exports = {level: 'info'};
```

TestController.js:

``` js
module.exports = {
  func: function (req, res) {
    sails.log.debug('This should get logged');
    // tl;dr: This gets logged when using vanilla sails, but not with this hook installed.
  }
}
```

**Comment by ghaiklor** [comment]
I assume it happens because winston doesn't have `debug` level.

**Comment by not-an-aardvark** [comment]
Thanks, that makes sense. It looks like `sails.log.warn()` does work with sails-hook-winston installed, so `debug` does seem to be a special case.

Would it be helpful to create a PR that allows for the `debug` log level?
