### ISSUE TITLE
Working with sails 1.0?

### ISSUE THREAD

**Issue by edencorbin** [Kikobeats/sails-hook-winston#18]
I believe my code matches the example with the exception of using a provided name rather then the package.json name, I am getting an error:

Code:

    var path = require('path');

    module.exports.log = {

    level: 'silly', // you are familiar with this value, right? 
    timestamp: true, // if you want to output the timestamp in the console transport 
   
    transports: [
      {
        module: require('winston-daily-rotate-file'),
        config: {
          dirname: path.resolve('logs'),
          datePattern: '.yyyy-MM-dd.log',
          filename: 'silly-logs',
          prettyPrint: true,
          timestamp: true,
          level: 'silly'
        }
      }
    ]

And Error:

`TypeError: Cannot set property DailyRotateFile of #<Object> which has only a getter`

I am using sails version 1.0.0-38, and my application is close to a newly generated project.

**Comment by Clan-Utility** [comment]
The problem is not with sails, but 'winston-daily-rotate-file'. I used winston-daily-rotate-file v1.0.1, and it works fine.

**Comment by edencorbin** [comment]
Great, I'll test this. Honestly its been so long, I think Winston is working just fine and I'm sails 1.0+ on all projects, thanks for getting back on this.
