### ISSUE TITLE
Full refactoring

### ISSUE THREAD

**Issue by ghaiklor** [Kikobeats/sails-hook-winston#3]
My proposal is:
- Rewrite to ES6 syntax;
- Update all dependencies;
- Integrate greenkeeper.io;
- Integrate Travis CI and Coveralls;

I can do all this by myself and will be easier if you add me to Collaborators, so I can manage updates and fixes.

**Comment by Kikobeats** [comment]
YES TO ALL!

I'm not currently working with sails, but in the past I created some libraries related with sails (since 0.11.x I remember). contributors are welcome, of course! :-)

**Comment by ghaiklor** [comment]
@Kikobeats great, thanks for your trust. I've added it in my checklist, so I'll update it when I have free time. Also, you can add me into collaborators in npm, so I'll not pinging you every time when I want to publish update :smiley_cat: 

P.S. I've written a lot modules for Sails and the best one is https://github.com/ghaiklor/generator-sails-rest-api. So I'm trying to keep up-to-date not only this one but other hooks that I'm using also.

**Comment by Kikobeats** [comment]
@ghaiklor in the past I tried to integrate coveralls with Coffeescript code. Do you know the state of this?

**Comment by ghaiklor** [comment]
@Kikobeats no, I don't. I've never written in Coffescript, only ES5\6. But, I suppose, there is no difference. Coveralls just take lcov report, so test coverage tool must support Coffeescript, not the Coveralls.

**Comment by ghaiklor** [comment]
@Kikobeats just pushed a few commits. The last thing is increate coverage.
