### ISSUE TITLE
Captains log not found

### ISSUE THREAD

**Issue by sschimmel** [Kikobeats/sails-hook-winston#9]
After I've installed sails-hook-winston my Sails app won't start anymore. It's missing captains log. This is caused by the way of requiring captains log in this module.

```
var captain     = require(path.resolve('node_modules/sails/node_modules/captains-log'));
```

This isn't supported anymore and should be changed to 

```
var captain     = require('captains-log');
```

Also var buildShipFn = require(path.resolve('node_modules/sails/lib/hooks/logger/ship')); isn't found and should be changed.

**Comment by ghaiklor** [comment]
@sschimmel yeah, because of npm 3 and flat tree. I will publish fix in few days or you can make PR and I will publish on weekends.

**Comment by ghaiklor** [comment]
@sschimmel I don't see any issues with that. Check your version. @Kikobeats did you publish update?

**Comment by ghaiklor** [comment]
Nope, he didn't. @Kikobeats I've asked you to add me to npm for this package, so I can publish updates. If you don't want to do this, add me to package.

**Comment by Kikobeats** [comment]
This change is necessary :+1: 

Maybe a little workaround would be:

``` js
var path = require('path')
var captain = require(path.resolve('node_modules', 'sails' , 'node_modules', 'captains-log'));
```

A little more clear, I think.

@ghaiklor do you need  any permissions?

BTW, create a PR and I can release it :-)

**Comment by ghaiklor** [comment]
@Kikobeats, I thought to publish master branch under 1.0.0. It's already fixed in the master branch for npm 3.

**Comment by Kikobeats** [comment]
go ahead! 😀

**Comment by ghaiklor** [comment]
@Kikobeats you don't understand what's going on, do you? I can't publish npm package because I don't have rights to do this :tired_face:

**Comment by Kikobeats** [comment]
ops, sorry, check now

**Comment by ghaiklor** [comment]
@Kikobeats yeah, works now :+1: 
@sschimmel published under 1.0.0.

**Comment by Kikobeats** [comment]
@ghaiklor for the releasing process, I use [bumped](https://github.com/bumped/bumped) check it next time (the project is [configured to use it](https://github.com/Kikobeats/sails-hook-winston/blob/master/.bumpedrc))

**Comment by ghaiklor** [comment]
@Kikobeats didn't know. I use semantic-release for these purposes.
